apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraftserverapi
  labels:
    app: minecraftserverapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraftserverapi
  template:
    metadata:
      labels:
        app: minecraftserverapi
    spec:
      containers:
      - name: minecraft-microservice
        # image: minecraftsaasregistry.azurecr.io/minecraft-microservice:latest
        image: federicoand98/weatherapi:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "0.3"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraftserverapi
spec:
  selector:
    app: minecraftserverapi
  ports:
    - protocol: TCP
      port: 80
